// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbh3jBsm0-ZLs3xO8wiewe7mh8PY-JxQk',
    appId: '1:811664004421:web:df186714cc905f5090da2c',
    messagingSenderId: '811664004421',
    projectId: 'prince-banner',
    authDomain: 'prince-banner.firebaseapp.com',
    storageBucket: 'prince-banner.firebasestorage.app',
    measurementId: 'G-PPEEFPS8CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRsOwfb_Sl-l8978W3hi8j38wq7EIC7I',
    appId: '1:811664004421:android:44ea540764a0949e90da2c',
    messagingSenderId: '811664004421',
    projectId: 'prince-banner',
    storageBucket: 'prince-banner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9QXbgDiZDyyC1pT8axhp0SNp8lKp1M1w',
    appId: '1:811664004421:ios:5e86f5e778103ce890da2c',
    messagingSenderId: '811664004421',
    projectId: 'prince-banner',
    storageBucket: 'prince-banner.firebasestorage.app',
    iosBundleId: 'com.pms.prince.pms',
  );
}
